# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: xiao_ble
    shield: swoop_dongle prospector_adapter
    artifact-name: swoop_dongle
  - board: nice_nano
    shield: swoop_left
    artifact-name: swoop_left
  - board: nice_nano
    shield: swoop_right
    artifact-name: swoop_right
  - board: nice_nano
    shield: settings_reset
    artifact-name: reset_keyboard
  - board: xiao_ble
    shield: settings_reset
    artifact-name: reset_dongle
